### ISSUE TITLE
User.java Dependency Inversion/ Single Responsibility w/ Order.java

### ISSUE THREAD

**Issue by tvtusc25** [tvtusc25/Group-Sprint-1-Bookazon#23]
### Problem:
- The `checkout()` function in `User.java` creates an `Order` object and handles checkout, which creates coupling and unnecessary responsibility.

**Comment by EliG03** [comment]
Should Order handle checkout instead?

**Comment by ryanmogauro** [comment]
I'm working on this rn, that's what I'm thinking
